package com.java.system.sessionagent.conversation.application;

public enum FeedbackCode {
    CATALOG_REQUIRED,
    INVALID_TOOL_INPUT,
    TOOL_INPUT_TOO_LARGE,
    UNKNOWN_REPOSITORY,
    REVISION_CHANGED,
    INVALID_CITATION,
    CALL_LIMIT_REACHED,
    MODEL_OUTPUT_INVALID,
    CONTEXT_TOO_LARGE,
    DATABASE_CONTRACT_ERROR,
    DEPENDENCY_UNAVAILABLE,
    DEPENDENCY_FORBIDDEN,
    DEPENDENCY_INVALID_RESPONSE
}
