package com.java.system.sessionagent.conversation.application;

public enum FeedbackCode {
    INVALID_TOOL_INPUT,
    TOOL_INPUT_TOO_LARGE,
    UNKNOWN_REPOSITORY,
    REVISION_OUTDATED,
    INDEX_NOT_READY,
    INDEX_CONTRACT_MISMATCH,
    CODE_FACT_NOT_FOUND,
    CODE_FACT_KIND_UNSUPPORTED,
    INVALID_QUERY,
    CALL_LIMIT_REACHED,
    MODEL_OUTPUT_INVALID,
    CONTEXT_TOO_LARGE,
    DATABASE_CONTRACT_ERROR,
    DEPENDENCY_UNAVAILABLE,
    DEPENDENCY_FORBIDDEN,
    DEPENDENCY_INVALID_RESPONSE
}
